[window]
padding = { x = 4, y = 2 }

[font]
normal = { family = 'AkkuratMono Nerd Font', style = 'Regular' }

offset = { x = 0, y = 2 }
size = 12

[colors.primary]
background = '#002B36'
foreground = '#A6B0B0'

# Normal colors
[colors.normal]
green  = '#9fb927'
blue   = '#4b9ffc'
cyan   = '#49b6a9'
red = '#e86c48'
yellow = '#d09a27'
magenta = '#cf598e'

# Bright colors
[colors.bright]
black   = '#4b93b5'
red     = '#cb4b16'
green   = '#586e75'
yellow  = '#b58802'
blue    = '#839496'
magenta = '#6c71c4'
cyan    = '#93a1a1'
white   = '#fdf6e3'

[colors.cursor]
text = 'CellForeground'
cursor = '#4E616A'

[mouse]
hide_when_typing = true

[env]
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
TERM_ALACRITTY='true'
#TERM='xterm-256color'
